<?xml version="1.0"?>
<package format="3">
  <name>line_fitting</name>
  <version>0.1.0</version>
  <description>ROS 2 Humble laser-scan line fitting example.</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
